ansible-lockdown/RHEL6-STIG

- tasks/cat3.yml
- tasks/prelim.yml
This should fix the samba issue when running this on CentOS. Stats for the config file and skips the samba lineinfile task should the config not exist. Fixes https://github.com/MindPointGroup/RHEL6-STIG/issues/2
> added check for samba

- defaults/main.yml
- files/disable-dccp.conf
- files/disable-rds.conf
- files/disable-sctp.conf
- files/disable-tipc.conf
- files/disable-usb.conf
- tasks/cat2.yml
- tasks/cat3.yml
On a minimal installation of RHEL 6, that doesn't include installing the NTP package, the playbook run will fail with cat2 true since there is no ntpd service to restart. Also, minor typo in the comments with packges/packages. Also closing cat 3 findings V-38516, V-38535, and V-38537.
> Installing NTP and 3x Cat 3 findings

- tasks/cat2.yml
- tasks/cat3.yml
- tasks/prelim.yml
For my proposed fix, I did a check for user accounts that are not root, then cross checked them against passwd for a UID < 500, since by the standards, 500+ belong to users and 499- should belong to system accounts on Red Hat systems. If someone goes against the standards, this will fail.
[Issue #25](https://github.com/MindPointGroup/RHEL6-STIG/issues/25)
> Non-system accounts lock out bug and closing 1 cat 3 finding

- defaults/main.yml
- tasks/cat2.yml
- templates/auditd.conf.j2
SV-50393r4_rule The system must require administrator action to unlock an account locked by excessive failed login attempts.
To configure the system to lock out accounts after a number of incorrect logon attempts and require an administrator to unlock the account using "pam_faillock.so", 
modify the content of both "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" as follows: 
Add the following line immediately before the "pam_unix.so" statement in the "AUTH" section: 
auth        required      pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900 
Add the following line immediately after the "pam_unix.so" statement in the "AUTH" section: 
auth        [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900 
Add the following line …
> This is a fix for release 8 of the STIG, and adds performance boost to auditd 

- tasks/cat2.yml
This resolves issue #27. If postfix is present when sendmail is removed, cronie
will not be removed.
> Ensure postfix is installed prior to removing sendmail

- library/pam.py
- tasks/cat2.yml
PAM Fixes include:
* The only modification that is made are to PAM module arguments. I previously had wrongly assumed that PAM entries were unique based on service, type and module, this has now been fixed to also key off the control.
* Converted file operations into Python 2.4 compatible code
* Improved documentation
* An issue where `before_line` placement was incorrectly inserting the compiled entry 2 lines prior instead of just 1.
* Some other minor fixes/improvements.
> SAVE_POINT: Updated cat2 and patched some bugs with the pam module

- tasks/cat2.yml
This was the error which was fixed:
TASK: [RHEL6-STIG | MEDIUM | V-38501 | AUDIT | The system must disable accounts after excessive login failures within a 15-minute interval.] *** 
<127.0.0.1> REMOTE_MODULE command grep -hG '^account\s*required\s*pam_faillock\.so' /etc/pam.d/system-auth /etc/pam.d/password-auth #USE_SHELL
failed: [centos6] => {"changed": false, "cmd": "grep -hG '^account\\s*required\\s*pam_faillock\\.so' /etc/pam.d/system-auth /etc/pam.d/password-auth", "delta": "0:00:00.005209", "end": "2016-04-24 07:13:33.143380", "rc": 1, "start": "2016-04-24 07:13:33.138171", "stdout_lines": [], "warnings": []}
FATAL: all hosts have already failed -- aborting
> fix for #53

- tasks/cat2.yml
Fixed issue where the backend command `sysctl -p` was throwing an error
about unknown keys. This is due to the particular kernal modules not
being loaded but is also not a fatal thing. Added `ignoreerrors` to the
V-38597 task as is the case with the other invocations of sysctl module
> BUGFIX: sysctl unknown keys

- library/pam.py
fixes #60 , and also fixes an issue where PAM rule arguments were being improperly interpreted as being correct when they were not; this was caused by a misuse of superset when it was subset that needed to be used when comparing the user supplied args with the args currently in the config
@bbaassssiiee would you mind giving this a spin and see if it works for you?
> Bugfix for pam module

- library/pam.py
The code did not check if modify_rule() replaced an existing line and inserted a second copy of the line if the before_line option was used.
> fix before_line replace logic

- tasks/cat3.yml
If "rpm --setugids" changes the user and group ownership of the file, it would clear any setuid and setgid bits. Running "rpm --setperms" afterwards fixes this.
> fix V-38453

- tasks/main.yml
The minor version number variable name, ansible.version, was incorrect. Additionally, the conditional did not accomplish its original goal of failing when the Ansible version is less than 2.1. This conditional statement accomplishes that goal.
> Correct version check conditional

- tasks/cat3.yml
Similar to the V-38452 AUDIT task, escapes in the regex_replace filter when used in a free-form argument syntax should consist of a single backslash.
Having two backslashes causes the regex match to fail, and the unfiltered item will be used (e.g. 'S.5....T.    /etc/rc.d/init.d/supervisord' is given to rpm instead of 'etc/rc.d/init.d/supervisord')
See https://github.com/ansible/ansible-modules-core/issues/5846
> Fixing V-38447 and V-38453 AUDIT tasks

- tasks/cat1.yml
- tasks/cat3.yml
When these strings are single quoted, we get a literaly '\t' string
where a TAB character is expected.  Double quoting does the expected
thing.  Tested with Ansible 2.1.0.0.
> Replace " for ' to expand tab characters

- tasks/cat2.yml
Existing tag "V-38573" belongs to another set of tasks. This corrects the tag to "V-38592"
> Tag mismatch on 1 of the 2 tasks for V-38592

- defaults/main.yml
- tasks/cat2.yml
Per RedHat 6 STIG V1R17:
V-38572: 'The "difok" parameter will indicate how many characters must differ. The DoD requires eight characters differ during a password change. This would appear as "difok=8".'
V-38658: 'must be a line beginning with "password required pam_pwhistory.so" or "password requisite pam_pwhistory.so" and end with "remember=5"'
I'd prefer if you merged my pull request rather than squashed it.
> STIG alignment: passwords

- tasks/prelim.yml
The current regex matches comments, which was throwing errors on my systems.  I changed the regex to only match non-comment lines.
> ignore comments in /etc/rsyslog*

- tasks/cat1.yml
The first commit preserves whitespace before 'nullok', and squashes whitespace after it.  Without this commit, the options string ends up with two spaces in a row when 'nullok' is removed.
The second commit adds "follow: yes" so that the replace module will follow the symlink and operate on the actual file, usually system-auth-ac, rather that replace the symlink with a modified copy of the file.  Ansible 2.5 removes the "follow" option entirely and always modifies the linked file (as if follow=yes)
I'd prefer if you merged my pull request rather than squashed it.
> system-auth nullok rule fixes

- defaults/main.yml
- tasks/cat2.yml
if we're setting one, we should set both, or otherwise check that
both settings are consistent
> auditd: fails to start if admin_space_left not less than space_left

- tasks/cat2.yml
If ipv6 isn't enabled, this task causes the role to error out (or at least it did on my system).
> only set policy for ipv6 when ipv6 actually required

- tasks/cat1.yml
The \s character set also matches newlines.  If nullok is the last
thing on a line, the following line is effectively removed by being
merged into the current line.  If this next line happens to be the
pam_deny.so line, auth always returns success.  The proper thing to
do here is to only match space and tab characters explicitly.
> dangerous regexp whitespace error, only match space/tab

- README.md
Remove link to nonexistent note. Fix typo.
> README.md: remove broken link, fix typo

- tasks/cat2.yml
the STIG V1R18 says to use "passwd -l <user>"
> fix password locking, improve check_mode

- tasks/cat2.yml
- tasks/cat3.yml
- ignore missing rsyslog-generated log files
- only 'yum reinstall' once per package, not once per file per package.  (No need to reinstall a package multiple times.)
- whitespace tweak
> Various Fixes 2018-04-18

- tasks/cat2.yml
The remediation steps in the STIG (V-38501 and friends) would only allow pam_unix.so.
A common use case for central auth requires pam_sss.so; this change allows that while still ensuring users are locked out as appropriate.  I'm not aware of any central auth setup that would be satisfied with only pam_unix.so.  These updated remediation tasks still pass the "Check Content" in the relevant faillock rules.
From V-38439 (CAT II):
> **Check Content:** Interview the SA to determine if there is an automated system for managing user accounts, preferably integrated with an existing enterprise user management system.
>
> If there is not, this is a finding.
>
> **Fix Text:** Implement an automated system for managing user accounts that minimizes the risk of errors, either intentional or deliberate. …
> pamd: reposition pam_faillock.so, allow more than just pam_unix.so

- tasks/cat2.yml
- tasks/prelim.yml
- consolidate boilerplate to prelim.yml
- allow selection of a subset of faillock rules
- re-order one of the rules to match the STIG example and satisfy the DISA Benchmark.
> pam_faillock refactor: DRY, increase flexibility

- tasks/cat3.yml
This fixes two errors:
1. The role was doing the inverse of what was requested by the `rhel6stig_rhnsatellite_required` configuration item, thus never running the rule by default.
2. The rhnsd service on RHEL 6 has a broken initscript that causes the ansible service module to fail every time.  Ignore these errors. (just a workaround)  The service is disabled by the task, it just might not take effect until a reboot.
> Fix rhnsd remediation

- tasks/cat2.yml
- tasks/cat3.yml
Audit both 32-bit and 64-bit syscalls on 64-bit systems.  The scap-security-guide project expects this everywhere.  DISA expects it on most rules.  I've made it configurable where DISA's check content doesn't explicitly require it.
> optionally audit b32 on b64
