- tasks/cat2.yml
- tasks/prelim.yml
Fixes https://github.com/MindPointGroup/RHEL6-STIG/issues/7
> Password locking changed_status fix

- tasks/cat2.yml
- tasks/prelim.yml
This reverts commit 12c992aba064036fcd8496f11a1ff2eed7b27978, reversing
changes made to 25a8ca33d4dcb3204160a6ebc25a8b4a3d345dda.
Did not solve original ticket.
> Revert "Merge pull request #8 from defionscode/Issue7_fix"

- tasks/cat3.yml
Fixes https://github.com/MindPointGroup/RHEL6-STIG/issues/6
> add check for rhnsd, fixes issue 6

- tasks/cat2.yml
- tasks/prelim.yml
Check this out, should do the trick. Tested for function and idempotency on my end.
> fix for issue 7, tested`

- defaults/main.yml
- files/disable-dccp.conf
- files/disable-sctp.conf
- files/disable-tipc.conf
- files/disable-usb.conf
- tasks/cat1.yml
- tasks/cat2.yml
This PR includes my fix for #13 and several fixes for Cat2 and Cat3 findings.
BTW: the kernel_blacklist is not picked up by the OSCAP audit tool, now using files.
> STIGMA Benchmark score: -H 100 -M 95 -L 92

- tasks/cat2.yml
- tasks/not_automated.yml
> SAVE_POINT: Continued refactor for cat2.yml

- files/disable-rds.conf
- tasks/cat3.yml
- tasks/not_automated.yml
- tasks/prelim.yml
> SAVE_POINT: cat3 refactor

- tasks/cat1.yml
- tasks/main.yml
- tasks/not_automated.yml
- tasks/prelim.yml
Working on issue #29.
Format tags and task name according to guidelines.
Reorder task so they run in sequential order by ID.
> Refactor cat1.yml

- files/sys_command_files_with_bad_owner.sh
- files/sys_command_files_with_bad_perms.sh
- files/sys_libs_with_bad_owner.sh
- files/sys_libs_with_bad_perms.sh
- tasks/cat2.yml
- tasks/not_automated.yml
- tasks/prelim.yml
This currently fails at an SMTP task which is past the refactor point.
> Save point for Refactor of Cat2

- tasks/cat1.yml
- tasks/cat2.yml
Refactor `cat2.yml` to use multi-line YAML and adhere to [coding standards](https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md).
See issue #29 for details.
> WIP: Refactor CAT II Tasks

- README.md
- defaults/main.yml
- files/disable-ipv6.conf
- handlers/main.yml
- meta/main.yml
- tasks/cat2.yml
- tasks/cat3.yml
- tasks/main.yml
- tasks/not_automated.yml
- tasks/prelim.yml
Refactor `cat2.yml` to use multi-line YAML and adhere to [coding standards](https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md).
See issue #29 for details.
> Refactor CAT II Tasks

- tasks/cat2.yml
> Fixing wrong tag

- tasks/cat1.yml
- tasks/cat2.yml
- tasks/cat3.yml
- tasks/main.yml
- tasks/post.yml
- tasks/prelim.yml
Correct some broken tasks referencing variables improperly.
Correct logic on the task that disables DHCP.
Properly format variables in `with_items` so they are no longer bare.
Rather than lots of tiny files used to disable kernel modules, switch to using the copy module with the content parameter.
Probably more by the time I'm done. 😄
> Several fixes

- tasks/cat2.yml
- tasks/cat3.yml
- tasks/prelim.yml
Fixed some issues with cat2. commented out sudoers psswd task as it breaks CI
> Update to cat2 and prelim

- README.md
- tasks/cat3.yml
- tasks/prelim.yml
- tests/README.md
- tests/apply_role.yml
- tests/deregister.yml
- tests/extra_vars_vagrant.yml
- tests/requirements.yml
- tests/role_idempotent_check.yml
- tests/vagrant-inventory
- tests/vagrant_provision.yml
- Update role to STIG V1R16
- Add local vagrant testing stuff
- Fix for #112 - non-idempotent task. Moved task to gather all setuid/gid files from prelim to directly before task that consumes that info
> V1r16 updates

- tasks/cat2.yml
> V-38477: corrected rule title

- tasks/cat2.yml
These 2 controls are unrelated
> Remove tag V-38492 from control V-38577

- tasks/prelim.yml
> remove check for removed rule

- README.md
- tasks/cat1.yml
- tasks/cat2.yml
> V1R17 changed virus scan from "high" to "medium"

- defaults/main.yml
- files/control-alt-delete.override
- tasks/cat1.yml
- tasks/cat2.yml
- removed virus scan requirement
- updated control-alt-delete logging faculty
- updated various rules to also check password-auth in addition to
system-auth
- improved pam_pwhistory arg placement
fixes #139
> updates for V1R19

- README.md
> python-jmespath required for json_query

- tasks/cat3.yml
> run rpm verify fixes once per RPM

- ansible.cfg
- tasks/cat2.yml
- tasks/cat3.yml
- tasks/main.yml
> fix ansible warnings

- tasks/cat2.yml
fixes #145
fix taken from https://github.com/MindPointGroup/RHEL7-STIG/pull/73
> safely enforce sudo password prompting

- .ansible-lint
- .yamllint
- LICENSE
- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/audit-cat1.yml
- tasks/audit-cat2.yml
- tasks/cat1.yml
- tasks/cat2.yml
- tasks/cat3.yml
- tasks/main.yml
- tasks/not_automated.yml
- tasks/post.yml
- tasks/prelim.yml
- tests/apply_role.yml
- tests/deregister.yml
- tests/extra_vars_vagrant.yml
- tests/requirements.yml
- tests/role_idempotent_check.yml
- tests/test.yml
- tests/vagrant-inventory
- tests/vagrant_provision.yml
Applied latest linting to system
yamllint and ansible lint included
test file updates
Testing: OS is EOL 
while it runs for any environment will require considerable setup.
- possible scenarios 
- Also only set to use older HostKeyAlgorithms 
- ssh-dsa and ssh-ksa (may cause issues on some machines)
possibly: override in ssh_config specific for host
- Many items may need to be skipped (if not local content for installing) which means that the control for installing and starting will miss the start element.
> Linting update - final release
